version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=yourpassword
      - PGDATABASE=uploads
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: uploads
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
